# Generated by Django 3.0.3 on 2020-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(max_length=10)),
                ('hora_termino', models.TimeField(max_length=10)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
